/*
	Nombre: Erick Octavio Nolasco Machuca
	Practica: 20
	Fecha: 3 de abril 2020
*/


/*1. CREA UNA BASE DE DATOS LLAMADAALUMNOSABD
CON LAA TABLAS CARRERAS, ALUMNOS, HORARIOACTUAL,
MATERIAS (CON PK Y FK)*/
CREATE DATABASE AlumnosABD
ON PRIMARY
(
	NAME = 'AlumnosABD.MDF',
	FILENAME = 'C:\BD\Particiones\AlumnosABD.MDF'
)
LOG ON
(
	NAME = 'AlumnosABD.LDF',
	FILENAME = 'C:\BD\Particiones\AlumnosABD.LDF'
)
go
USE AlumnosABD
GO
--Creacion de las tablas
CREATE TABLE MATERIA(
CODIGO_MATERIA INT NOT NULL  PRIMARY KEY,
NOMBRE VARCHAR(30),
CREDITOS TINYINT
)

CREATE TABLE CARRERA(
SIGLAS VARCHAR(5) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(70),
FECHAVIG DATE
)

CREATE TABLE ALUMNOS(
NC VARCHAR(8) NOT NULL PRIMARY KEY nonclustered, 
NOMBRE VARCHAR(80),
CARRERA VARCHAR(5) REFERENCES CARRERA(SIGLAS)
)

CREATE TABLE HORARIO_ACTUAL(
NC VARCHAR(8) REFERENCES ALUMNOS(NC),
MATERIA INT REFERENCES MATERIA(CODIGO_MATERIA),
HORA DATETIME,
PRIMARY KEY(NC,MATERIA)
)

/*Creacion de los grupos*/
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IE
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP ARQ
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IB
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IC
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IGE
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP II
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IM
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP IQ
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP ISC
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP TICS
GO
ALTER DATABASE ALUMNOSABD
	ADD FILEGROUP LA
GO
/*Relacionarlos*/
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IE.NDF',
	FILENAME='C:\BD\DISCO1\IE.NDF'
)TO FILEGROUP IE;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='ARQ.NDF',
	FILENAME='C:\BD\DISCO1\ARQ.NDF'
)TO FILEGROUP ARQ;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IB.NDF',
	FILENAME='C:\BD\DISCO1\IB.NDF'
)TO FILEGROUP IB;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IC.NDF',
	FILENAME='C:\BD\DISCO1\IC.NDF'
)TO FILEGROUP IC;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IGE.NDF',
	FILENAME='C:\BD\DISCO1\IGE.NDF'
)TO FILEGROUP IGE;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='II.NDF',
	FILENAME='C:\BD\DISCO1\II.NDF'
)TO FILEGROUP IM;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IQ.NDF',
	FILENAME='C:\BD\DISCO1\IQ.NDF'
)TO FILEGROUP IQ;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='ISC.NDF',
	FILENAME='C:\BD\DISCO1\ISC.NDF'
)TO FILEGROUP ISC;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='TICS.NDF',
	FILENAME='C:\BD\DISCO1\TICS.NDF'
)TO FILEGROUP TICS;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='IM.NDF',
	FILENAME='C:\BD\DISCO1\IM.NDF'
)TO FILEGROUP IM;
--
ALTER DATABASE ALUMNOSABD
ADD FILE
(
	NAME='LA.NDF',
	FILENAME='C:\BD\DISCO1\LA.NDF'
)TO FILEGROUP LA;

/*Crear la funcion de particion*/

CREATE PARTITION FUNCTION F_PCAR(varchar(5))
AS RANGE LEFT FOR VALUES ('IE','ARQ','IB','IC','IGE','II','IM','IQ','ISC','TICS')

/*esquema de particion*/

CREATE PARTITION SCHEME E_CAR
AS PARTITION F_PCAR
TO (IE,ARQ,IB,IC,IGE,II,IM,IQ,
ISC,TICS,LA)
go

/*Indice clusterado*/
CREATE CLUSTERED INDEX IDX_CARRERA
ON ALUMNOS(CARRERA)
ON E_CAR(CARRERA)
GO

/*Llenar la tabla carrera*/
INSERT INTO CARRERA 
VALUES
('IE','Ingenieria Electrica','01-01-26'),
('ARQ','ARQUITECTURA','01-01-26'),
('IB','INGENIERIA BIOQUIMICA','01-01-20'),
('IC','INGENIERIA CIVIL','01-01-20'),
('IGE','INGENIERIA EN GESTION','01-01-20'),
('II','Ingeniería Industrial','01-01-20'),
('IM','Ingeniería MECATRONICA','01-01-20'),
('IQ','Ingeniería QUIMICA','01-01-20'),
('ISC','Ingeniería en Sistemas Computacionales','01-01-20'),
('TICS','Ingeniería en Tecnología de la Información y Comunicaciones','01-01-20'),
('LA','Licenciatura en Administración','01-01-20')
go

/*3. INSERTA LOS ALUMNOS DE LAS LISTAS (CON BULK INSERT) DE QUE
SE TE SUBIRAN EN EL DRIVE (PREPARA LOS ARCHIVOS
ADECUADAMENTE COMO LO HICIMOS EL SEMESTRE PASADO) PERO
PONLES UNA CARRERAS DIFERENTES, NO TODOS SERAN DE
SISTEMAS.*/

bulk insert ALUMNOS
FROM 'C:\BD\Querys\ALUMNOS.txt'
WITH(
FIELDTERMINATOR=';',
ROWTERMINATOR='\n'
)

/*Consultar la tabla*/
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=1
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=2
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=3
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=4
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=5
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=6
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=7
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=8
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=9
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(CARRERA)=10
GO
SELECT * FROM ALUMNOS
WHERE $partition.F_PCAR(ID_CARRERA)=11
GO